name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches: [ "main" ]  # or whichever branch you want to trigger on

permissions:
  contents: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker compose build

      - name: Deploy MkDocs
        # We first configure Git to trust /docs inside the container, then run mkdocs gh-deploy
        run: |
          docker compose run --rm mkdocs bash -c " \
            git config --global --add safe.directory /docs && \
            mkdocs gh-deploy --force \
          "
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}