name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches: [ "main" ]  # or whichever branch you want to trigger on

# Give the workflow the necessary permissions
permissions:
  contents: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker compose build

      - name: Deploy MkDocs
        # Uses the same command you run locally
        run: docker compose run --rm mkdocs mkdocs gh-deploy --force
        env:
          # This makes the GitHub Actions-provided token 
          # available inside the container as GITHUB_TOKEN
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}